server:
  port: 8081

spring:
  datasource:
    # Docker container ip address and port
    url: jdbc:mysql://192.168.99.100:3306/db_example
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
      # schema will be automatically created afresh for every start of application
      ddl-auto: update #create-drop
      # Naming strategy
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      # Allows Hibernate to generate SQL optimized for a particular DBMS
      dialect: org.hibernate.dialect.MySQL5Dialect